# 我的yilia主题配置文件

menu:
  主页: /
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/xiaopin"
  weibo: "http://weibo.com/u/2637356434" 

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: more
fancybox: true
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /images/avatar.jpg

#是否开启分享
share_jia: true
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: '所有文章'
  tagcloud: '标签'
  friends: '友链'
  aboutme: '关于我'

friends:
  王巍博客: https://onevcat.com/#blog
  唐巧博客: http://www.devtang.com/
  廖雪峰的官方网站: http://www.liaoxuefeng.com/
  天狐博客: http://www.skyfox.org/
  Kitten博客: http://www.kittenyang.com/
  李忠(蘑菇街)博客: http://www.limboy.me/
  Sunnyyoung博客: https://blog.sunnyyoung.net/
  ObjC中国: https://objccn.io/
  NSHipster: http://nshipster.cn/
  阮一峰ECMAScript6入门: http://es6.ruanyifeng.com/
  Git Document: https://git-scm.com/book/zh/v2/
  图片在线压缩: https://tinypng.com/
  屏幕录制GIF: http://www.cockos.com/licecap/
  Apple Developer: https://developer.apple.com/library/
  App Store 审核指南: https://developer.apple.com/app-store/review/guidelines/cn/
  Google Developer: https://developers.google.cn/
  阿里巴巴矢量图标库: http://www.iconfont.cn/
  NSDate日期格式: http://www.nsdateformatter.com/
  iOS版本分布情况: https://developer.apple.com/support/app-store/
  iOS符号表: https://bugly.qq.com/docs/user-guide/symbol-configuration-ios/?v=20170627170213
  iPhone尺寸: https://developer.apple.com/library/content/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/Displays/Displays.html#//apple_ref/doc/uid/TP40013599-CH108-SW6
  JavaScript MDN Doc: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/

aboutme: 我是吴品诚，我喂自己袋盐......